src/Entity/ResEntreprise.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ResEntrepriseRepository")
 */
class ResEntreprise
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $ville;

    /**
     * @ORM\Column(type="text")
     */
    private $adresse;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ResDemande", mappedBy="entreprise")
     */
    private $resDemandes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ResDevis", mappedBy="entreprise")
     */
    private $resDevis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ResIntervention", mappedBy="entreprise")
     */
    private $resInterventions;

    public function __construct()
    {
        $this->resDemandes = new ArrayCollection();
        $this->resDevis = new ArrayCollection();
        $this->resInterventions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function __toString() {
        return $this->nom;
    }

    /**
     * @return Collection|ResDemande[]
     */
    public function getResDemandes(): Collection
    {
        return $this->resDemandes;
    }

    public function addResDemande(ResDemande $resDemande): self
    {
        if (!$this->resDemandes->contains($resDemande)) {
            $this->resDemandes[] = $resDemande;
            $resDemande->setEntreprise($this);
        }

        return $this;
    }

    public function removeResDemande(ResDemande $resDemande): self
    {
        if ($this->resDemandes->contains($resDemande)) {
            $this->resDemandes->removeElement($resDemande);
            // set the owning side to null (unless already changed)
            if ($resDemande->getEntreprise() === $this) {
                $resDemande->setEntreprise(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ResDevis[]
     */
    public function getResDevis(): Collection
    {
        return $this->resDevis;
    }

    public function addResDevi(ResDevis $resDevi): self
    {
        if (!$this->resDevis->contains($resDevi)) {
            $this->resDevis[] = $resDevi;
            $resDevi->setEntreprise($this);
        }

        return $this;
    }

    public function removeResDevi(ResDevis $resDevi): self
    {
        if ($this->resDevis->contains($resDevi)) {
            $this->resDevis->removeElement($resDevi);
            // set the owning side to null (unless already changed)
            if ($resDevi->getEntreprise() === $this) {
                $resDevi->setEntreprise(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ResIntervention[]
     */
    public function getResInterventions(): Collection
    {
        return $this->resInterventions;
    }

    public function addResIntervention(ResIntervention $resIntervention): self
    {
        if (!$this->resInterventions->contains($resIntervention)) {
            $this->resInterventions[] = $resIntervention;
            $resIntervention->setEntreprise($this);
        }

        return $this;
    }

    public function removeResIntervention(ResIntervention $resIntervention): self
    {
        if ($this->resInterventions->contains($resIntervention)) {
            $this->resInterventions->removeElement($resIntervention);
            // set the owning side to null (unless already changed)
            if ($resIntervention->getEntreprise() === $this) {
                $resIntervention->setEntreprise(null);
            }
        }

        return $this;
    }
}

src/Form/ResEntrepriseType.php
<?php

namespace App\Form;

use App\Entity\ResEntreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResEntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class, [
                'label' => 'Nom',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('ville',TextType::class, [
                'label' => 'Ville',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('adresse',TextType::class, [
                'label' => 'Adresse',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('code_postal',IntegerType::class, [
                'label' => 'Code postal',
                'attr' => ['class' => 'form-control'],
            ])
         //   ->add('submit',SubmitType::class, [
         //       'attr' => ['class' => 'btn btn-lg btn-success'],
         //   ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ResEntreprise::class,
        ]);
    }
}

src/Controller/ResEntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\ResEntreprise;
use App\Form\ResEntrepriseType;
use App\Repository\ResEntrepriseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/entreprise")
 */
class ResEntrepriseController extends AbstractController
{
    /**
     * @Route("/", name="res_entreprise_index", methods={"GET"})
     */
    public function index(ResEntrepriseRepository $resEntrepriseRepository): Response
    {
        return $this->render('res_entreprise/index.html.twig', [
            'res_entreprises' => $resEntrepriseRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="res_entreprise_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $resEntreprise = new ResEntreprise();
        $form = $this->createForm(ResEntrepriseType::class, $resEntreprise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($resEntreprise);
            $entityManager->flush();

            return $this->redirectToRoute('res_entreprise_index');
        }

        return $this->render('res_entreprise/new.html.twig', [
            'res_entreprise' => $resEntreprise,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="res_entreprise_show", methods={"GET"})
     */
    public function show(ResEntreprise $resEntreprise): Response
    {
        return $this->render('res_entreprise/show.html.twig', [
            'res_entreprise' => $resEntreprise,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="res_entreprise_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, ResEntreprise $resEntreprise): Response
    {
        $form = $this->createForm(ResEntrepriseType::class, $resEntreprise);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('res_entreprise_index');
        }

        return $this->render('res_entreprise/edit.html.twig', [
            'res_entreprise' => $resEntreprise,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/delete", name="res_entreprise_delete")
     */
    public function delete(Request $request, ResEntreprise $resEntreprise): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($resEntreprise);
        $entityManager->flush();

        return $this->redirectToRoute('res_entreprise_index');
    }
}

templates/res_entreprise/_delete_form.html.twig
<form method="post" action="{{ path('res_entreprise_delete', {'id': res_entreprise.id}) }}" onsubmit="return confirm('Vous etes sur de vouloir supprimer cette entreprise?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ res_entreprise.id) }}">
    <a class="btn btn-lg btn-primary" href="{{ path('res_entreprise_index') }}">Retour aux entreprises</a>
    <a class="btn btn-lg btn-success" href="{{ path('res_entreprise_edit', {'id': res_entreprise.id}) }}">Modifier</a>
    <button class="btn btn-lg btn-danger">Supprimer</button>
</form>

templates/res_entreprise/_form.html.twig
<div class="container">
    {{ form_start(form) }}
    <div class="form-row bg-dark">
        <div class="col text-white">
            {{ form_label(form.nom) }}
            {{ form_widget(form.nom) }}
        </div>
        <div class="col text-white">
            {{ form_label(form.ville) }}
            {{ form_widget(form.ville) }}
        </div>
    </div>
    <div class="form-row">
        <div class="col text-white">
            {{ form_label(form.adresse) }}
            {{ form_widget(form.adresse) }}
        </div>
        <div class="col text-white">
            {{ form_label(form.code_postal) }}
            {{ form_widget(form.code_postal) }}
        </div>
    </div>
    <br>
    <div class="col text-white">
        <a href="{{ path('res_entreprise_index') }}" class="btn btn-lg btn-primary">Revenir</a>
        <button class="btn btn-lg btn-success">{{ button_label|default('Valider') }}</button>
    </div>
    {{ form_end(form) }}
</div>

templates/res_entreprise/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ResEntreprise{% endblock %}

{% block body %}
    <div class="container full-height">
        <br>
    <h1 class="text-white">Modifier l'entreprise</h1>
        <br>

    {{ include('res_entreprise/_form.html.twig', {'button_label': 'Modifier'}) }}
    </div>
{% endblock %}

templates/res_entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Entreprises{% endblock %}

{% block body %}
<div class="container">
        <br>
        <h1 class="text-white">Entreprises</h1>
        <br>

        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Ville</th>
                <th>Adresse</th>
                <th>Code Postal</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for res_entreprise in res_entreprises %}
                <tr>
                    <td>{{ res_entreprise.nom }}</td>
                    <td>{{ res_entreprise.ville }}</td>
                    <td>{{ res_entreprise.adresse }}</td>
                    <td>{{ res_entreprise.codePostal }}</td>
                    <td>
                        <a href="{{ path('res_entreprise_show', {'id': res_entreprise.id}) }}"><i class="fa fa-search" style="font-size:26px;"></i></a>
                        <a href="{{ path('res_entreprise_edit', {'id': res_entreprise.id}) }}"><i class="fa fa-pencil-square" style="font-size:26px; color:orange"></i></a>
                        <a href="{{ path('res_entreprise_delete', {'id': res_entreprise.id}) }}"><i class="fa fa-minus-square" style="font-size:26px;color:red"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="text-align-left">
        <a href="{{ path('res_entreprise_new') }}" type="button" class="btn btn-lg btn-primary">Ajouter</a>
        </div>
        <br>
</div>
{% endblock %}

templates/res_entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ResEntreprise{% endblock %}

{% block body %}
    <div class="container full-height">
        <br>
    <h1 class="text-white">Ajout d'une nouvelle entreprise</h1>
        <br>

    {{ include('res_entreprise/_form.html.twig') }}
    </div>
{% endblock %}

templates/res_entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ResEntreprise{% endblock %}

{% block body %}
    <div class="container full-height">
        <br>
    <h1 class="text-white">Détails de l'entreprise</h1>
        <br>
    <table class="table table-dark table-striped">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ res_entreprise.nom }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ res_entreprise.ville }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ res_entreprise.adresse }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ res_entreprise.codePostal }}</td>
            </tr>
        </tbody>
    </table>

    {{ include('res_entreprise/_delete_form.html.twig') }}
    </div>
{% endblock %}